'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('orders', [
      {
        product_id: 3,
        product_flavour_id: 1,
        name: 'Order 1',
        slug: 'order-1',
        description: 'Sample order description',
        price: 100,
        discount_price: 98,
        category_id: 1,
        brand_id: 2,
        quantity: 2,
        user_id: 1,
        image_url: 'https://example.com/image1.jpg',
        payment_gateway: 'Stripe',
        transaction_id: 'txn_123456',
        order_status: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 4,
        product_flavour_id: 3,
        name: 'Order 2',
        slug: 'order-2',
        description: 'Another sample order',
        price: 200,
        discount_price: 150,
        category_id: 2,
        brand_id: 3,
        quantity: 1,
        user_id: 2,
        image_url: 'https://example.com/image2.jpg',
        payment_gateway: 'PayPal',
        transaction_id: 'txn_654321',
        order_status: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 3,
        product_flavour_id: 1,
        name: 'Order 1',
        slug: 'order-1',
        description: 'Sample order description',
        price: 100,
        discount_price: 98,
        category_id: 1,
        brand_id: 2,
        quantity: 2,
        user_id: 1,
        image_url: 'https://example.com/image1.jpg',
        payment_gateway: 'Stripe',
        transaction_id: 'txn_123456',
        order_status: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 5,
        product_flavour_id: 3,
        name: 'Order 2',
        slug: 'order-2',
        description: 'Another sample order',
        price: 200,
        discount_price: 150,
        category_id: 2,
        brand_id: 3,
        quantity: 1,
        user_id: 2,
        image_url: 'https://example.com/image2.jpg',
        payment_gateway: 'PayPal',
        transaction_id: 'txn_654321',
        order_status: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 5,
        product_flavour_id: 3,
        name: 'Order 2',
        slug: 'order-2',
        description: 'Another sample order',
        price: 200,
        discount_price: 150,
        category_id: 2,
        brand_id: 3,
        quantity: 1,
        user_id: 2,
        image_url: 'https://example.com/image2.jpg',
        payment_gateway: 'PayPal',
        transaction_id: 'txn_654321',
        order_status: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 5,
        product_flavour_id: 3,
        name: 'Order 2',
        slug: 'order-2',
        description: 'Another sample order',
        price: 200,
        discount_price: 150,
        category_id: 2,
        brand_id: 3,
        quantity: 1,
        user_id: 2,
        image_url: 'https://example.com/image2.jpg',
        payment_gateway: 'PayPal',
        transaction_id: 'txn_654321',
        order_status: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 5,
        product_flavour_id: 3,
        name: 'Order 2',
        slug: 'order-2',
        description: 'Another sample order',
        price: 200,
        discount_price: 150,
        category_id: 2,
        brand_id: 3,
        quantity: 1,
        user_id: 2,
        image_url: 'https://example.com/image2.jpg',
        payment_gateway: 'PayPal',
        transaction_id: 'txn_654321',
        order_status: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Add more sample orders as needed
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('orders', null, {});
  }
};